package net.runelite.client.plugins.autosarachnis;

public enum ASS {
    SPECIAL_ATTACK, FIND_BANK, DEPOSIT_ALL, EQUIP_MAINHAND, WITHDRAW_MAINHAND, EQUIP_OFFHAND, WITHDRAW_OFFHAND, WITHDRAW_SPEC_WEAPON, WITHDRAW_COMBAT_POTION, WITHDRAW_PRAYER_RESTORE, WITHDRAW_HOUSE_TELE, WITHDRAW_FOOD, FINISHED_WITHDRAWING, WALK_TO_DUNGEON, DESCEND_STAIRS, WITHDRAW_KNIFE, CUT_FIRST_WEB, CUT_SECOND_WEB, CUT_THIRD_WEB, WALK_TO_WEB, ENTER_BOSS_ROOM, PROTECT_FROM_MELEE, PROTECT_FROM_MISSILES, RESTORE_PRAYER, EAT_FOOD, TELE_TO_POH, DRINK_COMBAT_POT, TOGGLE_PIETY, TOGGLE_CHIVALRY, ATTACK_SARACHNIS, LOOT_SARACHNIS, USE_POOL, TRAVEL_BANK, WALK_TO_BOOTH, EQUIP_SPEC_WEAPON, EQUIP_WEAPONS, TIMEOUT
}
