package net.runelite.client.plugins.cssarachnishelper;

public enum SarachnisHelperState {
    TOGGLE_PIETY, TOGGLE_CHIVALRY, TOGGLE_RIGOUR, TOGGLE_AUGURY, PROTECT_FROM_MAGIC, PROTECT_FROM_MISSILES, PROTECT_FROM_MELEE, ATTACK_BOSS, EAT_FOOD, TELEPORT, RESTORE_PRAYER, DRINK_COMBAT, TIMEOUT
}
