package net.runelite.client.plugins.tbluedragons;

public enum tBlueDragonsState {
    HANDLE_BREAK, OPEN_BANK, WITHDRAW_ITEMS, CLOSE_BANK, USE_OBSTACLE, WALK_TO_DUNGEON, CLIMB_DOWN, USE_TUNNEL, DRINK_POTS, DRINK_COMBAT_POT, DRINK_PRAYER_POTS, DRINK_ANTIFIRE, TELEPORT_OUT, EAT_FOOD, ATTACK_DRAGON, HANDLE_PRAYER, LOOT_ITEMS, MOVING, SAFESPOT, TIMEOUT, LOOT_SCALES
}
